services:
  db:
    image: postgres:16
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "enpitsu", "-d", "enpitsu"]
      interval: 3s
      retries: 10
      start_period: 30s
    environment:
      POSTGRES_DB: enpitsu
      POSTGRES_USER: enpitsu
      POSTGRES_PASSWORD: enpitsu
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  cache:
    image: redis:6.2-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 1s
      timeout: 3s
      retries: 5
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass enpitsu --maxmemory-policy noeviction
    volumes:
      - cache:/data
    expose:
      - 6379

  web:
    container_name: enpitsu_admin
    image: rmecha/enpitsu:main
    restart: always
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://enpitsu:enpitsu@db:5432/enpitsu
      REDIS_URL: redis://:enpitsu@cache:6379/
      AUTH_URL: https://${ENPITSU_VIRTUAL_HOST}
      AUTH_SECRET: ${ENPITSU_AUTH_SECRET}
      AUTH_GOOGLE_ID: ${ENPITSU_AUTH_GOOGLE_ID}
      AUTH_GOOGLE_SECRET: ${ENPITSU_AUTH_GOOGLE_SECRET}
      CORS_ORIGIN: ${ENPITSU_CORS_ORIGIN}
      SPECIAL_ADMIN_USERS: ${ENPITSU_SPECIAL_ADMIN_USERS}
    ports:
      - 3000:3000

  processor:
    container_name: enpitsu_question_processor
    image: rmecha/enpitsu-processor:main
    restart: always
    volumes:
      - processor_log:/vote-processor/logs
    depends_on:
      web:
        condition: service_started
    environment:
      DATABASE_URL: postgresql://enpitsu:enpitsu@db:5432/enpitsu
      REDIS_URL: redis://:enpitsu@cache:6379/

  # The following are the needed services for Chibisafe file server:
  #   - sfs: Static File Server
  #   - chibisafe: Chibisafe Web Interface
  #   - chibisafe_server: Chibisafe Server
  sfs:
    image: halverneus/static-file-server:v1.8.3
    ports:
      - "8002:8080"
    volumes:
      - "chibisafe_uploads:/web"
    environment:
      - ALLOW_INDEX=false
      - SHOW_LISTING=false
    restart: unless-stopped

  chibisafe:
    image: chibisafe/chibisafe:latest
    environment:
      - BASE_API_URL=http://chibisafe_server:8000
    expose:
      - 8001
    ports:
      - 8001:8001
    restart: unless-stopped

  chibisafe_server:
    image: chibisafe/chibisafe-server:latest
    volumes:
      - chibisafe_db:/app/database:rw
      - chibisafe_uploads:/app/uploads:rw
      - chibisafe_logs:/app/logs:rw
    expose:
      - 8000
    ports:
      - 8000:8000
    restart: unless-stopped

volumes:
  db:
  cache:
  processor_log:
  chibisafe_db:
  chibisafe_uploads:
  chibisafe_logs:
